-- =============================================
-- ER Interiores 3D — Supabase PostgreSQL Schema
-- Execute este SQL no SQL Editor do Supabase
-- =============================================

-- 1. TABELA DE USUÁRIOS
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  name character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'client'
    CHECK (role IN ('admin', 'employee', 'client')),
  created_at timestamp with time zone DEFAULT now()
);

-- 2. TABELA DE CATÁLOGOS
CREATE TABLE public.catalogs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  description text,
  specialty character varying,
  experience character varying,
  city character varying,
  image character varying,
  rating numeric DEFAULT 5.0,
  projects integer DEFAULT 0,
  tags text[] DEFAULT '{}',
  created_at timestamp with time zone DEFAULT now()
);

-- 3. TABELA DE CHATS
CREATE TABLE public.chats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  catalog_id bigint NOT NULL REFERENCES public.catalogs(id) ON DELETE CASCADE,
  status character varying NOT NULL DEFAULT 'pending'
    CHECK (status IN ('active', 'pending', 'closed')),
  last_message text,
  last_message_time timestamp with time zone DEFAULT now(),
  unread integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- 4. TABELA DE MENSAGENS
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id bigint NOT NULL REFERENCES public.chats(id) ON DELETE CASCADE,
  sender_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- 5. TABELA DE PROJETOS
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  catalog_id bigint NOT NULL REFERENCES public.catalogs(id) ON DELETE CASCADE,
  title character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'completed')),
  value numeric,
  created_at timestamp with time zone DEFAULT now()
);

-- =============================================
-- ÍNDICES PARA PERFORMANCE
-- =============================================
CREATE INDEX idx_chats_client_id ON public.chats(client_id);
CREATE INDEX idx_chats_catalog_id ON public.chats(catalog_id);
CREATE INDEX idx_messages_chat_id ON public.messages(chat_id);
CREATE INDEX idx_messages_created_at ON public.messages(created_at);
CREATE INDEX idx_projects_client_id ON public.projects(client_id);
CREATE INDEX idx_projects_catalog_id ON public.projects(catalog_id);
CREATE INDEX idx_users_email ON public.users(email);
CREATE INDEX idx_users_role ON public.users(role);

-- =============================================
-- HABILITAR REALTIME NAS TABELAS DE CHAT
-- =============================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.chats;

-- =============================================
-- RLS (Row Level Security) — POLÍTICAS
-- =============================================

-- Habilitar RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- USERS: qualquer um pode ler (para exibir nomes), mas só admin edita
CREATE POLICY "users_select" ON public.users FOR SELECT USING (true);
CREATE POLICY "users_insert" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "users_update" ON public.users FOR UPDATE USING (true);
CREATE POLICY "users_delete" ON public.users FOR DELETE USING (true);

-- CATALOGS: todos leem, admin gerencia
CREATE POLICY "catalogs_select" ON public.catalogs FOR SELECT USING (true);
CREATE POLICY "catalogs_insert" ON public.catalogs FOR INSERT WITH CHECK (true);
CREATE POLICY "catalogs_update" ON public.catalogs FOR UPDATE USING (true);
CREATE POLICY "catalogs_delete" ON public.catalogs FOR DELETE USING (true);

-- CHATS: todos envolvidos podem ver
CREATE POLICY "chats_select" ON public.chats FOR SELECT USING (true);
CREATE POLICY "chats_insert" ON public.chats FOR INSERT WITH CHECK (true);
CREATE POLICY "chats_update" ON public.chats FOR UPDATE USING (true);
CREATE POLICY "chats_delete" ON public.chats FOR DELETE USING (true);

-- MESSAGES: todos envolvidos podem ver
CREATE POLICY "messages_select" ON public.messages FOR SELECT USING (true);
CREATE POLICY "messages_insert" ON public.messages FOR INSERT WITH CHECK (true);
CREATE POLICY "messages_update" ON public.messages FOR UPDATE USING (true);
CREATE POLICY "messages_delete" ON public.messages FOR DELETE USING (true);

-- PROJECTS: envolvidos podem ver
CREATE POLICY "projects_select" ON public.projects FOR SELECT USING (true);
CREATE POLICY "projects_insert" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "projects_update" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "projects_delete" ON public.projects FOR DELETE USING (true);

-- =============================================
-- VIEW: chats com nomes do cliente e catálogo
-- =============================================
CREATE OR REPLACE VIEW public.chats_with_names AS
SELECT
  c.*,
  u.name AS client_name,
  cat.name AS catalog_name
FROM public.chats c
JOIN public.users u ON u.id = c.client_id
JOIN public.catalogs cat ON cat.id = c.catalog_id;

-- =============================================
-- VIEW: mensagens com dados do remetente
-- =============================================
CREATE OR REPLACE VIEW public.messages_with_sender AS
SELECT
  m.*,
  u.name AS sender_name,
  u.role AS sender_role
FROM public.messages m
JOIN public.users u ON u.id = m.sender_id;

-- =============================================
-- VIEW: projetos com nomes
-- =============================================
CREATE OR REPLACE VIEW public.projects_with_names AS
SELECT
  p.*,
  u.name AS client_name,
  cat.name AS catalog_name
FROM public.projects p
JOIN public.users u ON u.id = p.client_id
JOIN public.catalogs cat ON cat.id = p.catalog_id;

-- =============================================
-- FUNÇÃO: atualizar last_message do chat
-- =============================================
CREATE OR REPLACE FUNCTION public.update_chat_last_message()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.chats
  SET last_message = NEW.content,
      last_message_time = NEW.created_at
  WHERE id = NEW.chat_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_new_message
  AFTER INSERT ON public.messages
  FOR EACH ROW
  EXECUTE FUNCTION public.update_chat_last_message();

-- =============================================
-- DADOS INICIAIS (SEED)
-- =============================================

-- Usuários de demo
INSERT INTO public.users (email, password, name, role) VALUES
  ('admin@erinteriores3d.com', 'admin123', 'Administrador', 'admin'),
  ('vendedor@erinteriores3d.com', 'vendedor123', 'João Vendedor', 'employee'),
  ('cliente@email.com', 'cliente123', 'Maria Cliente', 'client');

-- Catálogos
INSERT INTO public.catalogs (name, description, specialty, experience, city, rating, projects, tags) VALUES
  ('Design Elegância', 'Móveis planejados de alto padrão com design sofisticado e acabamento premium', 'Cozinhas Planejadas', '15 anos', 'São Paulo', 4.9, 248, ARRAY['Alto Padrão', 'Sob Medida']),
  ('Madeira Premium', 'Criações exclusivas com materiais nobres e técnicas artesanais de excelência', 'Móveis Rústicos', '20 anos', 'Curitiba', 4.8, 186, ARRAY['Artesanal', 'Madeira Maciça']),
  ('Contemporâneo', 'Linhas modernas e funcionais para espaços contemporâneos e dinâmicos', 'Home Office', '8 anos', 'Rio de Janeiro', 4.7, 124, ARRAY['Moderno', 'Funcional']),
  ('Clássicos Sutis', 'Tradição e qualidade em cada detalhe com acabamentos impecáveis', 'Quartos Planejados', '25 anos', 'Belo Horizonte', 4.9, 312, ARRAY['Clássico', 'Premium']),
  ('Inovação Móvel', 'Tecnologia e design integrados em soluções inteligentes de marcenaria', 'Closets', '12 anos', 'Porto Alegre', 4.6, 98, ARRAY['Tecnologia', 'Inovação']),
  ('Sustentável Design', 'Materiais conscientes e design responsável para ambientes equilibrados', 'Móveis Externos', '10 anos', 'Florianópolis', 4.8, 156, ARRAY['Sustentável', 'Ecológico']);
